import 'package:flutter/material.dart';
import 'package:myrestorent_app/Models/category.dart';
import 'package:myrestorent_app/Models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quik & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'hemburgers',
    color: Colors.blue,
  ),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.pink,
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.teal,
  ),
  Category(
    id: 'c7',
    title: 'Brackfast',
    color: Colors.yellow,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.green,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.black,
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.tealAccent,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
      'c3',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cook.fnr.sndimg.com/content/dam/images/cook/fullset/2011/1/4/0/CCEV102_Red-Sauce-and-Spaghetti_s4x3.jpg',
    duration: 20,
    ingredients: [
      '1 (28-ounce) can pelati tomatoes',
      '2 tablespoons extra-virgin olive oil, plus more for serving',
      '1/3 red onion, medium diced',
      '3 cloves garlic, sliced into chunks',
      'Pinch red pepper flakes',
      '2 handful fresh basil, torn, plus more for serving',
      'Salt and freshly ground black pepper',
      '1 pound spaghetti, for serving',
      'Freshly grated Parmesan cheese, for serving',
    ],
    steps: [
      'In a food processor, puree the tomatoes to a smooth creamy consistency.',
      'Add olive oil to a large pan over medium heat.',
      'Once hot, add the onions and saute until they are soft, and before it actually starts browning a bit, add the garlic.',
      'If you like to make the sauce spicier, add a pinch red pepper, optional.',
      'Add the tomatoes and season with salt and pepper.',
      'Simmer on a medium-low flame for about a half hour.',
      'Thrive for balance in the consistency of the sauce, it has to be fluid but it should not look overly wet.',
      'A few minutes before taking the sauce off the fire, add half the basil and season with salt and pepper.',
      'Cook a nice al dente pasta, dress with red sauce and finish with some freshly grated Parmesan.',
      'couple of leaves of basil and sprinkle with extra-virgin olive oil.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
      'c1',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://img.sndimg.com/food/image/upload/c_thumb,q_80,w_562,h_316/v1/img/recipes/42/33/94/picZdf8o1.jpg',
    duration: 10,
    ingredients: [
      'slice white bread or 1 slice wheat, sandwich',
      'butter',
      '1-2 slice low-sodium',
      '1 slice pineapple',
      '1 pinch dried marjoram',
      '1-2 slice cheese, to cover bread.',
    ],
    steps: [
      'Preheat oven to 350°F.',
      'Lightly butter both sides of the bread and place on cookie sheet.',
      'Layer ham then pineapple on one slice of bread.',
      'Sprinkle with marjoram and top with cheese.',
      'Bake for 7 to 12 minutes or until cheese is melted and sandwich is heated through.',
      'Serve hot.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/2294328.jpg',
    duration: 45,
    ingredients: [
      '1 egg',
      '1/2 teaspoon salt',
      '1/2 teaspoon ground black pepper',
      '1 pound ground beef',
      '1/2 cup fine dry bread crumbs',
    ],
    steps: [
      'Preheat an outdoor grill for high heat and lightly oil grate.',
      'In a medium bowl, whisk together egg, salt and pepper.',
      'Place ground beef and bread crumbs into the mixture.',
      'With hands or a fork, mix until well blended.',
      'Form into 4 patties approximately 3/4 inch thick.',
      'Place patties on the prepared grill.',
      'Cover and cook 6 to 8 minutes per side, or to desired doneness.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/398472.jpg',
    duration: 60,
    ingredients: [
      '2 pounds veal',
      '1 cup all-purpose flour',
      '4 eggs',
      '1 tablespoon vegetable oil',
      'salt and pepper to taste',
      '4 cups bread crumbs',
      '1/8 cup oil for frying',
    ],
    steps: [
      'Cut the veal into steaks, about as thick as your finger.',
      'Dredge in flour. In a shallow dish, beat the eggs with 1 tablespoon oil, salt and pepper.',
      'Coat the veal with egg mixture, then with bread crumbs.',
      'Heat 1/4 cup oil in a heavy skillet over medium heat.',
      'Fry veal until golden brown, about 5 minutes on each side.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/5382253.jpg',
    duration: 15,
    ingredients: [
      '1 pound potatoes',
      '7/8 cup heavy whipping cream',
      '1 small lemon, juiced',
      'salt and freshly ground black pepper to taste',
      '14 ounces smoked salmon, chopped',
      '1 tablespoon chopped fresh chives',
    ],
    steps: [
      'Place potatoes into a large pot and cover with salted water and bring to a boil.',
      'Reduce heat to medium-low and simmer until tender, 20 to 30 minutes. Drain and rinse under cold water.',
      'Peel potatoes once they are cool enough to handle and cut into cubes.',
      'Allow to cool.',
      'Combine cream, lemon juice, salt, and pepper in a small bowl.',
      'Place potatoes in the middle of a large serving platter and distribute smoked salmon on the edges.',
      'Pour cream dressing over potatoes, Sprinkle with chives.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Delicious Raspberry Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/6552480.jpg',
    duration: 240,
    ingredients: [
      '18 ounces fresh raspberries',
      '7 tablespoons sugar, or more as needed',
      '4 tablespoons orange juice',
      '1 (.25 ounce) package unflavored gelatin',
      '1 3/4 cups heavy cream',
      '2 tablespoons vanilla sugar',
      '1 dash lemon juice',
    ],
    steps: [
      'Set a few raspberries aside for garnish.',
      'Combine remaining raspberries and sugar in a bowl, mix, and set aside for 30 minutes.',
      'Pass raspberries through a sieve to strain out seeds. Discard seeds.',
      'Pour orange juice into a small saucepan and sprinkle gelatin on top.',
      'Set aside for 1 minute.',
      'Heat over low temperature without boiling until gelatin is fully dissolved, about 3 minutes.',
      'Remove from stove, allow to cool slightly and mix with raspberry puree.',
      'Beat cream in a chilled glass or metal bowl using an electric mixer until frothy.',
      'Add vanilla sugar gradually, continuing to beat until soft peaks form.',
      'Fold whipped cream into raspberry puree.',
      'Stir in lemon juice and sweeten with more sugar if desired.',
      'Cover and refrigerate for 2 hours. Garnish with raspberries.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/4074772.jpg',
    duration: 20,
    ingredients: [
      '1 cup sifted self-rising flour',
      '1 cup milk',
      '1 egg',
      '2 tablespoons vegetable oil',
    ],
    steps: [
      'Beat eggs, oil, and milk together, and add to flour.',
      'Stir until combined.',
      'Heat a greased griddle until drops of water sprinkled on it evaporate noisily.',
      'Pour 1/8 to 1/4 cup batter onto the griddle.',
      'Turn over with a metal spatula when bubbles begin to form on top.',
      'Cook second side to a golden brown color.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/300x300/5504832.jpg',
    duration: 35,
    ingredients: [
      '2 tablespoons ghee (clarified butter)',
      '1 onion, finely chopped',
      '4 cloves garlic, minced',
      '1 tablespoon ground cumin',
      '1 teaspoon salt',
      '1 teaspoon ground ginger',
      '1 teaspoon cayenne pepper',
      '½ teaspoon ground cinnamon',
      '¼ teaspoon ground turmeric',
      '1 (14 ounce) can tomato sauce',
      '1 cup heavy whipping cream',
      '2 teaspoons paprika',
      '1 tablespoon white sugar',
      '1 tablespoon vegetable oil',
      '4 skinless, boneless chicken breast halves, cut into bite-size pieces',
      '½ teaspoon curry powder',
      '½ teaspoon salt, or to taste (optional)',
      '1 teaspoon white sugar, or to taste (optional)',
    ],
    steps: [
      'Heat ghee in a large skillet over medium heat and cook and stir onion until translucent, about 5 minutes.',
      'Stir in garlic; cook and stir just until fragrant, about 1 minute.',
      'Stir cumin, 1 teaspoon salt, ginger, cayenne pepper, cinnamon, and turmeric into the onion mixture; fry until fragrant, about 2 minutes.',
      'Stir tomato sauce into the onion and spice mixture, bring to a boil, and reduce heat to low.',
      'Simmer sauce for 10 minutes, then mix in cream, paprika, and 1 tablespoon sugar.',
      'Bring sauce back to a simmer and cook, stirring often, until sauce is thickened, 10 to 15 minutes.',
      'Heat vegetable oil in a separate skillet over medium heat.',
      'Stir chicken into the hot oil, sprinkle with curry powder, and sear chicken until lightly browned but still pink inside, about 3 minutes; stir often.',
      'Transfer chicken and any pan juices into the sauce.',
      'Simmer chicken in sauce until no longer pink, about 30 minutes; adjust salt and sugar to taste.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/4479094.jpg',
    duration: 45,
    ingredients: [
      '1 teaspoon melted butter, or as needed',
      '2 tablespoons white sugar',
      '2 ounces 70% dark chocolate, broken into pieces',
      '1 tablespoon butter',
      '1 tablespoon all-purpose flour',
      '4 1/3 tablespoons cold milk',
      '1 pinch salt',
      '1 pinch cayenne pepper',
      '1 large egg yolk',
      '2 large egg whites',
      '1 pinch cream of tartar',
      '1 tablespoon white sugar, divided',
    ],
    steps: [
      'Preheat oven to 375 degrees F (190 degrees C).',
      'Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 (5-ounce) ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins.',
      'Rotate ramekins until sugar coats all surfaces. Pour off extra sugar.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Do not let water boil or come to a simmer.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour.',
      'Whisk until flour is incorporated into butter and mixture thickens, about 1 minute. Reduce heat to low.',
      'Whisk in cold milk until mixture becomes smooth and thickens, 2 or 3 minutes. Remove skillet from heat.',
      'Transfer mixture to bowl with melted chocolate.',
      'Add salt and very small pinch of cayenne pepper.',
      'Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar.',
      'Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix, 2 or 3 minutes.',
      'Add 1/3 of sugar and whisk in.',
      'Whisk in a bit more sugar about 15 seconds; whisk in the rest of the sugar.',
      'Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate, 1 or 2 minutes.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears.',
      'Divide mixture between 2 prepared ramekins.',
      'Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparagus Salad with Cherry Tomatoes',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://images.media-allrecipes.com/userphotos/560x315/5264207.jpg',
    duration: 30,
    ingredients: [
      '1 tablespoon extra-virgin olive oil, or more as needed',
      '1 clove garlic, minced',
      '1 pound asparagus spears, trimmed and cut into 1-inch pieces',
      'salt to taste',
      '1 squeeze lemon juice, or to taste',
      '1 (10 ounce) basket cherry tomatoes, halved',
      '2 tablespoons white balsamic vinegar',
      '1 teaspoon Dijon mustard',
      '1 teaspoon white sugar',
      '1/2 teaspoon salt',
      '4 tablespoons extra-virgin olive oil',
    ],
    steps: [
      'Heat olive oil in a large skillet over medium heat and cook garlic until fragrant, about 30 seconds.',
      'Add asparagus and stir-fry until tender but still firm to the bite, 5 to 7 minutes.',
      'Season with salt and drizzle with lemon juice.',
      'Place in a bowl and add cherry tomatoes.',
      'Stir vinegar, mustard, sugar, and salt together in a small bowl.',
      'Pour in olive oil and mix well.',
      'Drizzle dressing over asparagus and tomatoes and mix well.',
      'Serve warm.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];
